"""Cleanup superfluous test data — keeps structural collections, indexes,
admin, real user-created rooms/tournaments/leagues, and the 2026-27 calendar.

Detects test-generated data by naming pattern (short prefix + hex suffix).
Usage:
    python scripts/cleanup_test_data.py --dry-run    # preview only
    python scripts/cleanup_test_data.py --apply      # actually delete
"""
import asyncio
import os
import re
import sys
import argparse
from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv()

# Names looking like test data: prefix (letters+optional digit) + [_-] + hex suffix
TEST_NAME_RE = re.compile(
    r"^("
    r"BN|BNSAL|BNSV|BNFG\d?|BNTIK|R\d|SVR|SAL|FG|"
    r"bn|srv|hist|del1|link|lock|INV"
    r")[_\-][0-9a-fA-F]{3,8}$"
)
# Also short throwaway names generated by parallel tests:
EXTRA_NAMES = {
    "SVR-A", "SVR-B", "RENAMED", "WithBadPicks", "OneShot", "T1",
    "Torneo Vecchio", "SwitchStar", "Empty",
}

# Usernames generated by test fixtures — broad pattern to catch all
# short random-suffixed usernames from parallel pytest runs.
TEST_USER_RE = re.compile(
    r"^("
    # Explicit prefixes used by fixtures, with optional single-letter suffix
    # and hex-random tail. Covers: svr_a_XXXX, svi_c_XXXX, sum1_XXXX, etc.
    r"svr|svi|bn|hist|inv|del1|salp|svp|out|TEST|test|player|dummy|fixture|"
    r"fgA|fgB|suA|suB|bugA|bugB|rvA|rvB|sum\d?|o|fga|fgb|sua|sub"
    r")([_\-][a-z])?[_\-]?[0-9a-fA-F]{3,10}$"
)

REAL_SEASON = "2026-27"
ADMIN_EMAIL = "verone.salvatore@libero.it"


def is_test_name(name: str | None) -> bool:
    if not name:
        return False
    if name in EXTRA_NAMES:
        return True
    return bool(TEST_NAME_RE.match(name))


async def main(apply: bool):
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ.get("DB_NAME", "test_database")]
    plan = {}

    # ---------------- Calendar ----------------
    plan["sal_calendar"] = await db.sal_calendar.count_documents(
        {"season": {"$ne": REAL_SEASON}}
    )

    # ---------------- Rooms (Tiket) ----------------
    rooms_to_delete: list[str] = []
    async for r in db.rooms.find({}, {"id": 1, "name": 1, "_id": 0}):
        if is_test_name(r.get("name")):
            rooms_to_delete.append(r["id"])
    plan["rooms"] = len(rooms_to_delete)

    # ---------------- SAL tournaments ----------------
    sal_to_delete: list[str] = []
    async for t in db.sal_tournaments.find({}, {"id": 1, "name": 1, "season": 1, "_id": 0}):
        if is_test_name(t.get("name")) or (t.get("season") and t["season"] != REAL_SEASON):
            sal_to_delete.append(t["id"])
    plan["sal_tournaments"] = len(sal_to_delete)

    # ---------------- SV tournaments ----------------
    sv_to_delete: list[str] = []
    async for t in db.sv_tournaments.find({}, {"id": 1, "name": 1, "season": 1, "_id": 0}):
        if is_test_name(t.get("name")) or (t.get("season") and t["season"] != REAL_SEASON):
            sv_to_delete.append(t["id"])
    plan["sv_tournaments"] = len(sv_to_delete)

    # ---------------- FG leagues ----------------
    fg_to_delete: list[str] = []
    async for lg in db.fg_leagues.find({}, {"id": 1, "name": 1, "_id": 0}):
        if is_test_name(lg.get("name")):
            fg_to_delete.append(lg["id"])
    plan["fg_leagues"] = len(fg_to_delete)

    # ---------------- Bonus tables ----------------
    # Configs/picks/credits from test seasons OR referring to deleted rooms/tournaments
    plan["bonus_configs"] = await db.bonus_configs.count_documents(
        {"season": {"$ne": REAL_SEASON}}
    )
    plan["bonus_picks"] = await db.bonus_picks.count_documents(
        {"$or": [
            {"season": {"$ne": REAL_SEASON}},
            {"subscription_id": {"$in": rooms_to_delete + sal_to_delete + sv_to_delete + fg_to_delete}},
        ]}
    )
    plan["bonus_credits"] = await db.bonus_credits.count_documents(
        {"$or": [
            {"season": {"$ne": REAL_SEASON}},
            {"room_id": {"$in": rooms_to_delete}},
        ]}
    )

    # ---------------- Test users ----------------
    test_users: list[str] = []
    async for u in db.users.find({}, {"id": 1, "username": 1, "email": 1, "_id": 0}):
        if u.get("email") == ADMIN_EMAIL:
            continue
        uname = u.get("username") or ""
        if TEST_USER_RE.match(uname):
            test_users.append(u["id"])
    plan["users"] = len(test_users)

    # ---------------- Preview ----------------
    print("=" * 60)
    print("CLEANUP PLAN (dry-run):" if not apply else "APPLYING CLEANUP:")
    print("=" * 60)
    for k, v in plan.items():
        print(f"  {k:.<40} {v:>6} to delete")
    print("=" * 60)
    print(f"KEEPING: admin user, {REAL_SEASON} calendar, ~"
          f"{await db.rooms.count_documents({}) - len(rooms_to_delete)} rooms, "
          f"~{await db.sal_tournaments.count_documents({}) - len(sal_to_delete)} SAL tournaments, "
          f"~{await db.sv_tournaments.count_documents({}) - len(sv_to_delete)} SV tournaments, "
          f"~{await db.fg_leagues.count_documents({}) - len(fg_to_delete)} FG leagues, "
          f"~{await db.users.count_documents({}) - len(test_users)} users")
    print("=" * 60)

    if not apply:
        # Show a sample of what would be deleted (for user validation)
        async def sample(name, ids, coll):
            if not ids:
                return
            samples = [d async for d in db[coll].find(
                {"id": {"$in": ids[:5]}}, {"name": 1, "_id": 0}
            )]
            print(f"  Sample {name}: {[s.get('name') for s in samples]}")
        await sample("rooms", rooms_to_delete, "rooms")
        await sample("sal_tournaments", sal_to_delete, "sal_tournaments")
        await sample("sv_tournaments", sv_to_delete, "sv_tournaments")
        await sample("fg_leagues", fg_to_delete, "fg_leagues")
        print("\nRun with --apply to execute the cleanup.")
        return

    # ---------------- APPLY ----------------
    print("\nExecuting deletions...")

    # Sal calendar (non-real seasons)
    r = await db.sal_calendar.delete_many({"season": {"$ne": REAL_SEASON}})
    print(f"  sal_calendar: {r.deleted_count}")

    # Rooms + dependents
    if rooms_to_delete:
        await db.rooms.delete_many({"id": {"$in": rooms_to_delete}})
        await db.memberships.delete_many({"room_id": {"$in": rooms_to_delete}})
        await db.schedine.delete_many({"room_id": {"$in": rooms_to_delete}})
        await db.invites.delete_many({"room_id": {"$in": rooms_to_delete}})
        print(f"  rooms (+ memberships/schedine/invites): {len(rooms_to_delete)}")

    # SAL tournaments + dependents
    if sal_to_delete:
        await db.sal_tournaments.delete_many({"id": {"$in": sal_to_delete}})
        await db.sal_participants.delete_many({"tournament_id": {"$in": sal_to_delete}})
        await db.sal_matchdays.delete_many({"tournament_id": {"$in": sal_to_delete}})
        await db.sal_picks.delete_many({"tournament_id": {"$in": sal_to_delete}})
        await db.sal_invites.delete_many({"tournament_id": {"$in": sal_to_delete}})
        print(f"  sal_tournaments (+ deps): {len(sal_to_delete)}")

    # SV tournaments + dependents
    if sv_to_delete:
        await db.sv_tournaments.delete_many({"id": {"$in": sv_to_delete}})
        await db.sv_participants.delete_many({"tournament_id": {"$in": sv_to_delete}})
        await db.sv_matchdays.delete_many({"tournament_id": {"$in": sv_to_delete}})
        await db.sv_picks.delete_many({"tournament_id": {"$in": sv_to_delete}})
        await db.sv_invites.delete_many({"tournament_id": {"$in": sv_to_delete}})
        print(f"  sv_tournaments (+ deps): {len(sv_to_delete)}")

    # FG leagues + dependents
    if fg_to_delete:
        await db.fg_leagues.delete_many({"id": {"$in": fg_to_delete}})
        await db.fg_memberships.delete_many({"league_id": {"$in": fg_to_delete}})
        await db.fg_lineups.delete_many({"league_id": {"$in": fg_to_delete}})
        await db.fg_matchday_results.delete_many({"league_id": {"$in": fg_to_delete}})
        await db.fg_teams.delete_many({"league_id": {"$in": fg_to_delete}})
        await db.fg_invites.delete_many({"league_id": {"$in": fg_to_delete}})
        print(f"  fg_leagues (+ deps): {len(fg_to_delete)}")

    # Bonus
    r = await db.bonus_configs.delete_many({"season": {"$ne": REAL_SEASON}})
    print(f"  bonus_configs: {r.deleted_count}")
    r = await db.bonus_picks.delete_many({
        "$or": [
            {"season": {"$ne": REAL_SEASON}},
            {"subscription_id": {"$in": rooms_to_delete + sal_to_delete + sv_to_delete + fg_to_delete}},
        ]
    })
    print(f"  bonus_picks: {r.deleted_count}")
    r = await db.bonus_credits.delete_many({
        "$or": [
            {"season": {"$ne": REAL_SEASON}},
            {"room_id": {"$in": rooms_to_delete}},
        ]
    })
    print(f"  bonus_credits: {r.deleted_count}")

    # Test users
    if test_users:
        await db.users.delete_many({"id": {"$in": test_users}})
        # Cleanup any leftover picks/memberships tied to those users
        await db.memberships.delete_many({"user_id": {"$in": test_users}})
        await db.sal_participants.delete_many({"user_id": {"$in": test_users}})
        await db.sv_participants.delete_many({"user_id": {"$in": test_users}})
        await db.fg_memberships.delete_many({"user_id": {"$in": test_users}})
        await db.bonus_picks.delete_many({"user_id": {"$in": test_users}})
        print(f"  users (+ orphan memberships): {len(test_users)}")

    print("\n✅ Cleanup complete.")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--apply", action="store_true", help="actually delete (default: dry-run)")
    args = p.parse_args()
    asyncio.run(main(args.apply))
