"""Seed data for Serie A 2024/25 - approx 10 players per team."""

TEAMS = [
    "Inter", "Milan", "Juventus", "Napoli", "Atalanta", "Roma", "Lazio",
    "Fiorentina", "Bologna", "Torino", "Udinese", "Genoa", "Verona",
    "Cagliari", "Lecce", "Parma", "Empoli", "Como", "Monza", "Venezia"
]

# Role codes: P (Portiere), D (Difensore), C (Centrocampista), A (Attaccante)
PLAYERS = [
    # Inter
    ("Yann Sommer", "Inter", "P"),
    ("Alessandro Bastoni", "Inter", "D"),
    ("Benjamin Pavard", "Inter", "D"),
    ("Federico Dimarco", "Inter", "D"),
    ("Denzel Dumfries", "Inter", "D"),
    ("Nicolo Barella", "Inter", "C"),
    ("Hakan Calhanoglu", "Inter", "C"),
    ("Henrikh Mkhitaryan", "Inter", "C"),
    ("Lautaro Martinez", "Inter", "A"),
    ("Marcus Thuram", "Inter", "A"),
    # Milan
    ("Mike Maignan", "Milan", "P"),
    ("Theo Hernandez", "Milan", "D"),
    ("Fikayo Tomori", "Milan", "D"),
    ("Malick Thiaw", "Milan", "D"),
    ("Emerson Royal", "Milan", "D"),
    ("Tijjani Reijnders", "Milan", "C"),
    ("Youssouf Fofana", "Milan", "C"),
    ("Christian Pulisic", "Milan", "C"),
    ("Rafael Leao", "Milan", "A"),
    ("Alvaro Morata", "Milan", "A"),
    # Juventus
    ("Michele Di Gregorio", "Juventus", "P"),
    ("Gleison Bremer", "Juventus", "D"),
    ("Federico Gatti", "Juventus", "D"),
    ("Andrea Cambiaso", "Juventus", "D"),
    ("Pierre Kalulu", "Juventus", "D"),
    ("Manuel Locatelli", "Juventus", "C"),
    ("Douglas Luiz", "Juventus", "C"),
    ("Khephren Thuram", "Juventus", "C"),
    ("Dusan Vlahovic", "Juventus", "A"),
    ("Kenan Yildiz", "Juventus", "A"),
    # Napoli
    ("Alex Meret", "Napoli", "P"),
    ("Amir Rrahmani", "Napoli", "D"),
    ("Alessandro Buongiorno", "Napoli", "D"),
    ("Giovanni Di Lorenzo", "Napoli", "D"),
    ("Leonardo Spinazzola", "Napoli", "D"),
    ("Stanislav Lobotka", "Napoli", "C"),
    ("Andre-Frank Zambo Anguissa", "Napoli", "C"),
    ("Scott McTominay", "Napoli", "C"),
    ("Khvicha Kvaratskhelia", "Napoli", "A"),
    ("Romelu Lukaku", "Napoli", "A"),
    # Atalanta
    ("Marco Carnesecchi", "Atalanta", "P"),
    ("Isak Hien", "Atalanta", "D"),
    ("Sead Kolasinac", "Atalanta", "D"),
    ("Berat Djimsiti", "Atalanta", "D"),
    ("Davide Zappacosta", "Atalanta", "D"),
    ("Marten de Roon", "Atalanta", "C"),
    ("Ederson", "Atalanta", "C"),
    ("Mario Pasalic", "Atalanta", "C"),
    ("Ademola Lookman", "Atalanta", "A"),
    ("Mateo Retegui", "Atalanta", "A"),
    # Roma
    ("Mile Svilar", "Roma", "P"),
    ("Gianluca Mancini", "Roma", "D"),
    ("Evan Ndicka", "Roma", "D"),
    ("Zeki Celik", "Roma", "D"),
    ("Angelino", "Roma", "D"),
    ("Lorenzo Pellegrini", "Roma", "C"),
    ("Bryan Cristante", "Roma", "C"),
    ("Manu Kone", "Roma", "C"),
    ("Paulo Dybala", "Roma", "A"),
    ("Artem Dovbyk", "Roma", "A"),
    # Lazio
    ("Ivan Provedel", "Lazio", "P"),
    ("Alessio Romagnoli", "Lazio", "D"),
    ("Mario Gila", "Lazio", "D"),
    ("Nuno Tavares", "Lazio", "D"),
    ("Adam Marusic", "Lazio", "D"),
    ("Nicolo Rovella", "Lazio", "C"),
    ("Mattia Zaccagni", "Lazio", "C"),
    ("Matteo Guendouzi", "Lazio", "C"),
    ("Boulaye Dia", "Lazio", "A"),
    ("Taty Castellanos", "Lazio", "A"),
    # Fiorentina
    ("David De Gea", "Fiorentina", "P"),
    ("Luca Ranieri", "Fiorentina", "D"),
    ("Pietro Comuzzo", "Fiorentina", "D"),
    ("Dodo", "Fiorentina", "D"),
    ("Robin Gosens", "Fiorentina", "D"),
    ("Danilo Cataldi", "Fiorentina", "C"),
    ("Rolando Mandragora", "Fiorentina", "C"),
    ("Albert Gudmundsson", "Fiorentina", "C"),
    ("Moise Kean", "Fiorentina", "A"),
    ("Andrea Colpani", "Fiorentina", "A"),
    # Bologna
    ("Lukasz Skorupski", "Bologna", "P"),
    ("Sam Beukema", "Bologna", "D"),
    ("Jhon Lucumi", "Bologna", "D"),
    ("Charalampos Lykogiannis", "Bologna", "D"),
    ("Emil Holm", "Bologna", "D"),
    ("Remo Freuler", "Bologna", "C"),
    ("Lewis Ferguson", "Bologna", "C"),
    ("Riccardo Orsolini", "Bologna", "C"),
    ("Santiago Castro", "Bologna", "A"),
    ("Dan Ndoye", "Bologna", "A"),
    # Torino
    ("Vanja Milinkovic-Savic", "Torino", "P"),
    ("Alessandro Buongiorno-T", "Torino", "D"),
    ("Ricardo Rodriguez", "Torino", "D"),
    ("Saul Coco", "Torino", "D"),
    ("Adrien Tameze", "Torino", "D"),
    ("Ivan Ilic", "Torino", "C"),
    ("Samuele Ricci", "Torino", "C"),
    ("Nikola Vlasic", "Torino", "C"),
    ("Duvan Zapata", "Torino", "A"),
    ("Antonio Sanabria", "Torino", "A"),
    # Udinese
    ("Razvan Sava", "Udinese", "P"),
    ("Jaka Bijol", "Udinese", "D"),
    ("Kingsley Ehizibue", "Udinese", "D"),
    ("Jordan Zemura", "Udinese", "D"),
    ("Oumar Solet", "Udinese", "D"),
    ("Sandi Lovric", "Udinese", "C"),
    ("Jurgen Ekkelenkamp", "Udinese", "C"),
    ("Florian Thauvin", "Udinese", "C"),
    ("Lorenzo Lucca", "Udinese", "A"),
    ("Keinan Davis", "Udinese", "A"),
    # Genoa
    ("Nicola Leali", "Genoa", "P"),
    ("Johan Vasquez", "Genoa", "D"),
    ("Koni De Winter", "Genoa", "D"),
    ("Aaron Martin", "Genoa", "D"),
    ("Alessandro Vogliacco", "Genoa", "D"),
    ("Morten Frendrup", "Genoa", "C"),
    ("Milan Badelj", "Genoa", "C"),
    ("Ruslan Malinovskyi", "Genoa", "C"),
    ("Andrea Pinamonti", "Genoa", "A"),
    ("Vitinha", "Genoa", "A"),
    # Verona
    ("Lorenzo Montipo", "Verona", "P"),
    ("Diego Coppola", "Verona", "D"),
    ("Pawel Dawidowicz", "Verona", "D"),
    ("Jackson Tchatchoua", "Verona", "D"),
    ("Reda Belahyane", "Verona", "C"),
    ("Antoine Bernede", "Verona", "C"),
    ("Suat Serdar", "Verona", "C"),
    ("Casper Tengstedt", "Verona", "A"),
    ("Tijjani Noslin", "Verona", "A"),
    ("Daniel Mosquera", "Verona", "A"),
    # Cagliari
    ("Elia Caprile", "Cagliari", "P"),
    ("Yerry Mina", "Cagliari", "D"),
    ("Sebastiano Luperto", "Cagliari", "D"),
    ("Adam Obert", "Cagliari", "D"),
    ("Zito Luvumbo", "Cagliari", "C"),
    ("Nadir Zortea", "Cagliari", "C"),
    ("Antoine Makoumbou", "Cagliari", "C"),
    ("Roberto Piccoli", "Cagliari", "A"),
    ("Gianluca Gaetano", "Cagliari", "A"),
    ("Nicolas Viola", "Cagliari", "C"),
    # Lecce
    ("Wladimiro Falcone", "Lecce", "P"),
    ("Federico Baschirotto", "Lecce", "D"),
    ("Kialonda Gaspar", "Lecce", "D"),
    ("Antonino Gallo", "Lecce", "D"),
    ("Jean Rouyard", "Lecce", "D"),
    ("Ylber Ramadani", "Lecce", "C"),
    ("Balthazar Pierret", "Lecce", "C"),
    ("Medon Berisha", "Lecce", "C"),
    ("Nikola Krstovic", "Lecce", "A"),
    ("Tete Morente", "Lecce", "A"),
    # Parma
    ("Zion Suzuki", "Parma", "P"),
    ("Alessandro Circati", "Parma", "D"),
    ("Botond Balogh", "Parma", "D"),
    ("Enrico Delprato", "Parma", "D"),
    ("Adrian Benedyczak", "Parma", "A"),
    ("Adrian Bernabe", "Parma", "C"),
    ("Simon Sohm", "Parma", "C"),
    ("Nahuel Estevez", "Parma", "C"),
    ("Ange-Yoan Bonny", "Parma", "A"),
    ("Dennis Man", "Parma", "A"),
    # Empoli
    ("Devis Vasquez", "Empoli", "P"),
    ("Sebastiano Luperto-E", "Empoli", "D"),
    ("Ardian Ismajli", "Empoli", "D"),
    ("Saba Goglichidze", "Empoli", "D"),
    ("Pietro Pellegri", "Empoli", "A"),
    ("Jacopo Fazzini", "Empoli", "C"),
    ("Youssef Maleh", "Empoli", "C"),
    ("Liberato Cacace", "Empoli", "D"),
    ("Emmanuel Gyasi", "Empoli", "A"),
    ("Sebastian Esposito", "Empoli", "A"),
    # Como
    ("Pepe Reina", "Como", "P"),
    ("Alberto Dossena", "Como", "D"),
    ("Edoardo Goldaniga", "Como", "D"),
    ("Alessandro Moreo", "Como", "A"),
    ("Ivan Azon", "Como", "A"),
    ("Nicolas Paz", "Como", "C"),
    ("Maximo Perrone", "Como", "C"),
    ("Sergi Roberto", "Como", "C"),
    ("Patrick Cutrone", "Como", "A"),
    ("Andrea Belotti", "Como", "A"),
    # Monza
    ("Stefano Turati", "Monza", "P"),
    ("Armando Izzo", "Monza", "D"),
    ("Pablo Mari", "Monza", "D"),
    ("Andrea Carboni", "Monza", "D"),
    ("Georgios Kyriakopoulos", "Monza", "D"),
    ("Matteo Pessina", "Monza", "C"),
    ("Roberto Gagliardini", "Monza", "C"),
    ("Daniel Maldini", "Monza", "C"),
    ("Milan Djuric", "Monza", "A"),
    ("Dany Mota", "Monza", "A"),
    # Venezia
    ("Filip Stankovic", "Venezia", "P"),
    ("Marin Sverko", "Venezia", "D"),
    ("Michael Svoboda", "Venezia", "D"),
    ("Ridgeciano Haps", "Venezia", "D"),
    ("Domagoj Bradaric", "Venezia", "D"),
    ("Hans Nicolussi Caviglia", "Venezia", "C"),
    ("Alfred Duncan", "Venezia", "C"),
    ("Issa Doumbia", "Venezia", "C"),
    ("Joel Pohjanpalo", "Venezia", "A"),
    ("Gaetano Oristanio", "Venezia", "A"),
]
